### ISSUE TITLE
Vagrant-vmware-utility  has failed automated validation

### ISSUE THREAD

**Issue by leander091** [StefanScherer/choco-vagrant-vmware-utility#14]
Hi,

It looks like the latest versions ( 1.0.15 -  1.0.17) of the package won't pass the automated validation anymore.

Can you take a look?

Thanks in advance

**Comment by StefanScherer** [comment]
Thanks for the heads-up. I already feared that something might go wrong when I push several package versions in parallel.
I  have to slowly re-push them one after another to Chocolatey and wait for the approval.

**Comment by StefanScherer** [comment]
The three versions are approved.
